index:
   path: /
   controller: App\Controller\MainController::home

idea_show:
    path:       /subject/{subject_id}/situation/{situation_id}
    controller: App\Controller\MainController::showIdea
    methods:    GET|HEAD
    requirements:
        subject_id: '\d+'
        situation_id: '\d+'

dashboard:
    path: /dashboard
    controller: App\Controller\SubmissionsController::showDashboard
